### PR TITLE
Diseasestatus

### PR DESCRIPTION
**Pull request by saulakravitz**
SHould be reviewed by Martin and Sharon.

1) Added a new DiseaseStatus profile based on mCODE
2) Adds an extension to reference a Treatment Volume (mCODE STU3 will facilitate this, so extension will be shortlived)
3) Adds a qualifier on the statustrend for type of progression (local, nodal, etc).

### CODE REVIEW

**Review by mvonsieb — APPROVED** [review]
Structurally, the changes look good to me. The relation to RadiotherapyVolumes should be better described, I mean under which condition which volume is expected to be referenced. I am not sure if the granularity of volumes to which we prescribe, plan, deliver dose is the same as the targets for which progression will be assessed. But trial use should show that.

**Comment by saulakravitz** [comment]
> 

Is the description just as you wrote:   We aren't really sure, but we hope that usage will illuminate?

**Comment by mvonsieb** [comment]
Yes, let's assume that usage will show. Having and implementation that can link disease status to the same volumes are prescription and treatment summary, or even can annotate volumes at all may take some time. My comment was because I expected something more on the description of the reference. For example: "SHOULD reference all Radiotherapy Volumes for to which this status observation applies"? or "SHOULD reference all Radiotherapy Volumes that were considered to assess the status"? or something like that.

**Comment by mvonsieb** [comment]
Ready to be merged.

**Pull request merged**
